CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_courses_name UNIQUE (name)
);

CREATE TABLE seasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    riot_season_id VARCHAR(50),
    start_date DATE NOT NULL,
    end_date DATE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_seasons_name UNIQUE (name),
    CONSTRAINT uk_seasons_riot_season_id UNIQUE (riot_season_id),
    CONSTRAINT chk_seasons_date_range CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses (id),
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ranking_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX idx_users_course_id ON users (course_id);
CREATE INDEX idx_users_ranking_eligible ON users (ranking_eligible) WHERE ranking_eligible = TRUE;
CREATE UNIQUE INDEX uk_seasons_single_active ON seasons (active) WHERE active = TRUE;

CREATE TABLE ranked_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE riot_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users (id),
    ranked_stats_id BIGINT UNIQUE REFERENCES ranked_stats (id),
    puuid VARCHAR(100),
    game_name VARCHAR(100),
    tag_line VARCHAR(10),
    region VARCHAR(10)
);

CREATE UNIQUE INDEX uk_riot_accounts_puuid ON riot_accounts (puuid) WHERE puuid IS NOT NULL;
