CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    riot_match_id VARCHAR(30) NOT NULL,
    riot_account_id BIGINT NOT NULL REFERENCES riot_accounts (id),
    season_id BIGINT NOT NULL REFERENCES seasons (id),
    game_start TIMESTAMP NOT NULL,
    game_duration INT NOT NULL,
    queue_type VARCHAR(30) NOT NULL,
    win BOOLEAN NOT NULL,
    champion_id INT NOT NULL,
    role VARCHAR(20),
    kills INT NOT NULL,
    deaths INT NOT NULL,
    assists INT NOT NULL,
    cs INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_matches_riot_match_id UNIQUE (riot_match_id)
);

CREATE INDEX idx_matches_riot_account_id ON matches (riot_account_id);
CREATE INDEX idx_matches_season_id ON matches (season_id);
