CREATE TABLE player_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    riot_account_id BIGINT NOT NULL UNIQUE REFERENCES riot_accounts (id),
    season_id BIGINT NOT NULL REFERENCES seasons (id),
    total_games INT NOT NULL DEFAULT 0,
    wins INT NOT NULL DEFAULT 0,
    losses INT NOT NULL DEFAULT 0,
    win_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    primary_role VARCHAR(20),
    most_played_champion_id INT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
